@host = localhost:51483

### POST
POST http://{{host}}/api/Url
Content-Type: application/json

"http://www.google.com"

### GET
@code = 161701943
GET http://{{host}}/api/Url/{{code}}

###

GET http://{{host}}/test/encode?url=http://awww.google.com
